name: Dart & Flutter CI

# Trigger on push or pull request to main and dev branches
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install specific Flutter version (bundles Dart 3.8.1)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'  # Flutter version with Dart 3.8.1

      # Enable flutter analytics opt-out (optional)
      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      # Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run code formatting check (optional)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze the project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test
