name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'

      # Install dependencies
      - name: Get dependencies
        run: flutter pub get

      # Analyze project source
      - name: Analyze project
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Optional: Verify formatting
      # - name: Check formatting
      #   run: flutter format --set-exit-if-changed .
