name: Dart & Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '^3.8.1'

      # Verify Flutter setup
      - name: Flutter doctor
        run: flutter doctor

      # Get project dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Dart analyzer
      - name: Analyze project
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # Optional: check formatting
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
