name: Flutter CI

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/flutter
          key: flutter-sdk-${{ runner.os }}-stable
          restore-keys: |
            flutter-sdk-${{ runner.os }}-

      # Install Flutter SDK (stable)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Disable Flutter analytics
      - run: flutter config --no-analytics

      # Cache pub packages
      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test --coverage

      # Optional: Verify code formatting
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .
