const List<String> productivityTips = [
  "Take short breaks every hour to refresh your mind.",
  "Prioritize tasks by importance, not urgency.",
  "Eliminate distractions to maintain deep focus.",
  "Review your goals daily to stay on track.",
  "Set clear, achievable goals for the day.",
  "Use the Pomodoro technique to stay productive.",
  "Plan your day the night before.",
  "Break tasks into smaller, manageable steps.",
  "Keep your workspace organized.",
  "Avoid multitasking to maintain focus.",
  "Track your time to identify productivity leaks.",
  "Batch similar tasks together for efficiency.",
  "Use a digital or physical planner consistently.",
  "Start your day with the most important task.",
  "Limit social media usage during work hours.",
  "Set deadlines for tasks, even if not required.",
  "Practice mindfulness to reduce stress.",
  "Delegate tasks when possible.",
  "Stay hydrated to maintain focus.",
  "Take short walks to stimulate creativity.",
  "Listen to focus-enhancing music or white noise.",
  "Keep a notebook handy to capture ideas.",
  "Automate repetitive tasks whenever possible.",
  "Use keyboard shortcuts to save time.",
  "Start with the hardest task first ('Eat the Frog').",
  "Set realistic time estimates for tasks.",
  "Track your accomplishments daily.",
  "Use two-minute rule: if it takes less than 2 mins, do it now.",
  "Limit unnecessary meetings or calls.",
  "Declutter your digital files regularly.",
  "Turn off unnecessary notifications.",
  "Create a morning routine to start productive.",
  "Use end-of-day review to plan tomorrow.",
  "Batch email replies at specific times.",
  "Focus on one task until completion.",
  "Avoid checking email first thing in the morning.",
  "Use color coding for tasks or notes.",
  "Keep your phone out of reach when focusing.",
  "Set weekly goals, not just daily.",
  "Break long projects into milestones.",
  "Use habit tracking apps to reinforce routines.",
  "Reward yourself after completing important tasks.",
  "Start meetings with a clear agenda.",
  "Learn to say no to low-priority requests.",
  "Keep a consistent sleep schedule.",
  "Exercise regularly to boost energy.",
  "Use the 80/20 rule: focus on tasks that matter most.",
  "Limit decision fatigue by simplifying choices.",
  "Use a timer to create urgency and focus.",
  "Review and update your to-do list daily.",
  "Take micro-breaks to stretch or breathe.",
  "Use visual reminders for important tasks.",
  "Eliminate non-essential tasks.",
  "Write down ideas instead of keeping them in your head.",
  "Prioritize deep work over shallow tasks.",
  "Set boundaries with colleagues or family.",
  "Use 'Do Not Disturb' mode strategically.",
  "Schedule challenging tasks when energy is highest.",
  "Review goals weekly and adjust priorities.",
  "Learn keyboard shortcuts for productivity apps.",
  "Avoid perfectionism; focus on completion.",
  "Break up long meetings with activity breaks.",
  "Use templates for repetitive work.",
  "Delegate decision-making when appropriate.",
  "Batch phone calls to save time.",
  "Keep frequently used tools within reach.",
  "Avoid multitasking while learning something new.",
  "Simplify your task management system.",
  "Set clear start and end times for tasks.",
  "Use sticky notes for high-priority reminders.",
  "Declutter your workspace weekly.",
  "Listen to podcasts or audiobooks during commute.",
  "Avoid checking your phone first thing in the morning.",
  "Organize tasks by context, not just priority.",
  "Set achievable micro-goals for complex projects.",
  "Limit scrolling on social media apps.",
  "Use focus apps to block distractions.",
  "Plan breaks with a purpose (walk, meditate).",
  "Use calendar blocks to protect focused time.",
  "Track progress visually with charts or graphs.",
  "Reflect on productivity at the end of each week.",
  "Batch errands together to save time.",
  "Use checklists to avoid forgetting steps.",
  "Use recurring reminders for regular tasks.",
  "Learn to recognize low-energy times.",
  "Prioritize tasks that create impact.",
  "Keep a ‘done’ list to visualize achievements.",
  "Reduce decision fatigue by standardizing routines.",
  "Use templates for emails or reports.",
  "Avoid unnecessary context switching.",
  "Take vacations or breaks to recharge.",
  "Automate bill payments and recurring tasks.",
  "Use keyboard macros for repetitive work.",
  "Break large projects into daily actionable steps.",
  "Celebrate small wins to maintain motivation.",
  "Keep a clean inbox with zero inbox method.",
  "Practice single-tasking instead of multitasking.",
  "Use digital tools to track progress, not just paper.",
  "Focus on outcome, not just output.",
  "Learn to quickly estimate task durations.",
  "Prioritize high-value tasks in the morning.",
  "Keep a list of ongoing projects visible.",
  "Use color coding to quickly identify priorities.",
  "Set intentions at the start of each day.",
  "Visualize completing tasks to boost motivation.",
  "Learn keyboard shortcuts to speed up workflow.",
  "Avoid overloading your schedule; leave gaps.",
  "Break creative work into sprints.",
  "Keep healthy snacks nearby to maintain energy.",
  "Listen to productivity or educational podcasts.",
  "Use music that enhances focus.",
  "Limit context-switching by batching similar tasks.",
  "Track personal performance metrics.",
  "Reflect on completed tasks and lessons learned.",
  "Use mind maps to organize complex ideas.",
  "Have a defined end-of-day routine.",
  "Use sticky notes sparingly to highlight priorities.",
  "Practice gratitude to maintain a positive mindset.",
  "Review your calendar daily to avoid surprises.",
  "Use technology to automate reminders.",
  "Create boundaries between work and rest.",
  "Maintain a healthy work-life balance.",
  "Delegate effectively to free up high-value time.",
  "Review long-term goals weekly to stay aligned.",
  "Prioritize learning over busy work.",
  "Track both time spent and results achieved.",
  "Simplify decision-making with templates and routines.",
  "Eliminate energy-draining tasks where possible.",
];
